Improve the uptime test (#11)

diff --git a/.github/workflows/uptime.yml b/.github/workflows/uptime.yml
--- a/.github/workflows/uptime.yml
+++ b/.github/workflows/uptime.yml
@@ -5,6 +5,9 @@ permissions:
   contents: read
 
 on:
+  pull_request:
+    paths:
+      - .github/workflows/uptime.yml
   workflow_call:
     inputs:
       location:
@@ -15,11 +18,15 @@ on:
 env:
   RESOURCE_GROUP: c-aci-dashboard
   UPTIME_HRS: 48
+  LOCATION: ${{ inputs.location || 'westeurope' }}
 
 jobs:
 
   cleanup-deployed:
     runs-on: ubuntu-latest
+    continue-on-error: true
+    outputs:
+      deployments-matrix: ${{ steps.delete-containers.outputs.deployments-matrix }}
     steps:
       - name: Log into Azure
         uses: azure/login@v2
@@ -29,29 +36,52 @@ jobs:
           subscription-id: ${{ vars.SUBSCRIPTION }}
 
       - name: Delete Old Container Groups
+        id: delete-containers
         run: |
           CONTAINERS=$(az container list \
             --resource-group $RESOURCE_GROUP \
-            --query "[?starts_with(name, 'uptime-') && location=='${{ inputs.location }}']")
+            --query "[?starts_with(name, 'uptime-') && location=='${{ env.LOCATION }}']")
+
+          currentContainerCount=0
 
           for container in $(echo $CONTAINERS | jq -r '.[].id'); do
             echo "checking $container"
-            creationTime=$(date -d $(az container show --resource-group $RESOURCE_GROUP --ids $container --query "containers[0].instanceView.events" --output json | jq -r 'min_by(.firstTimestamp) | .firstTimestamp') +%s)
+            creationTime=$(date -d $(az container show --ids $container --query "containers[0].instanceView.events" --output json | jq -r 'min_by(.firstTimestamp) | .firstTimestamp') +%s)
             containerAge=$(( ($(date -u +"%s") - $creationTime) / 3600 ))
             echo "creationTime=$creationTime"
             echo "containerAge=$containerAge hours"
             if [ $containerAge -gt ${{ env.UPTIME_HRS }} ]; then
                 echo "Deleting container group: ${container}"
-                az resource delete --resource-group $RESOURCE_GROUP --name $container --resource-type Microsoft.ContainerInstance/containerGroups
+                az resource delete --ids $container
+            else
+                currentContainerCount=$((currentContainerCount + 1))
             fi
           done
 
+          deploymentsNeeded=$(((48 / 24 + 1) - $currentContainerCount))
+          echo "deploymentsNeeded=$deploymentsNeeded"
+          echo "deployments-matrix=[$(seq -s, 1 $deploymentsNeeded)]" >> $GITHUB_OUTPUT
+
+  deploy-new:
+    needs: cleanup-deployed
+    if: ${{ always() && needs.cleanup-deployed.outputs.deployments-matrix != '[]' }}
+    secrets: inherit
+    strategy:
+      fail-fast: false
+      matrix:
+        idx: ${{ fromJson(needs.cleanup-deployed.outputs.deployments-matrix) }}
+    uses: ./.github/workflows/workload-long-lived.yml
+    with:
+      id: uptime-${{ matrix.idx }}
+      location: ${{ inputs.location || 'westeurope' }}
+      cleanup: false
+
   check-deployed:
     runs-on: ubuntu-latest
-    needs: cleanup-deployed
+    needs:
+      - cleanup-deployed
+      - deploy-new
     if: always()
-    outputs:
-      deployment-needed: ${{ steps.check-container-liveness.outputs.deployment-needed }}
     steps:
       - name: Log into Azure
         uses: azure/login@v2
@@ -61,52 +91,40 @@ jobs:
           subscription-id: ${{ vars.SUBSCRIPTION }}
 
       - name: Check Deployed Containers
-        id: check-container-liveness
         run: |
           CONTAINERS=$(az container list \
             --resource-group $RESOURCE_GROUP \
-            --query "[?starts_with(name, 'uptime-') && location=='${{ inputs.location }}']")
+            --query "[?starts_with(name, 'uptime-') && location=='${{ env.LOCATION }}']")
 
           echo $CONTAINERS
 
           if [ -z "$CONTAINERS" ]; then
             echo "No containers found"
-            exit 0
+            exit 1
           fi
 
           BAD_STATES=("Killed" "Stopped" "Failed")
 
-          currentContainerCount=0
-
           for container in $(echo $CONTAINERS | jq -r '.[].id'); do
-            echo "checking $container"
-            containerJson=$(az container show --resource-group $RESOURCE_GROUP --ids $container)
-            creationTime=$(date -d $(az container show --resource-group $RESOURCE_GROUP --ids $container --query "containers[0].instanceView.events" --output json | jq -r 'min_by(.firstTimestamp) | .firstTimestamp') +%s)
-            containerAge=$(( ($(date -u +"%s") - $creationTime) / 3600 ))
-            echo "creationTime=$creationTime"
-            echo "containerAge=$containerAge hours"
+            echo "Checking $container"
+            containerJson=$(az container show --ids $container)
+            containerCreate=$(date -d $(echo $containerJson | jq -r '.containers[0].instanceView.events' | jq -r 'min_by(.firstTimestamp) | .firstTimestamp') +%s)
+            containerAge=$(( ($(date -u +"%s") - $containerCreate) / 3600 ))
+            echo "  Age: $containerAge hours"
             if [ $containerAge -lt ${{ env.UPTIME_HRS }} ]; then
-              currentContainerCount=$((currentContainerCount + 1))
-              echo "Checking for bad states"
-              for BAD_STATE in "${BAD_STATES[@]}"; do
-                if echo $containerJson | jq -r '.containers[].instanceView.events[].name' | grep $BAD_STATE; then
-                  echo "Container group: ${container} has been killed within 48 hours:"
-                  echo "Cleaning up failing container group"
-                  az resource delete --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name $container --resource-type Microsoft.ContainerInstance/containerGroups
-                  exit 1
-                fi
+              echo "  Container is less than ${{ env.UPTIME_HRS }} hours old, checking for bad states:"
+              containerStates=$(echo $containerJson | jq -r '.containers[0].instanceView.events[].name')
+              echo "  All states: $(echo $containerStates | tr '\n' ' ')"
+              for containerState in $containerStates; do
+                for badState in "${BAD_STATES[@]}"; do
+                  if [[ "$containerState" == "$badState" ]]; then
+                    echo "    This group entered the failure state "$badState" in the last 48 hours"
+                    echo "    Cleaning up failed group and exiting with error"
+                    az resource delete --ids $container
+                    exit 1
+                  fi
+                done
               done
+              echo "  No bad states found"
             fi
           done
-
-          echo "deployment-needed=$(($currentContainerCount < 3 ? 1 : 0))" >> $GITHUB_OUTPUT
-
-  deploy-new:
-    needs: check-deployed
-    if: ${{ always() && needs.check-deployed.outputs.deployment-needed == '1' }}
-    secrets: inherit
-    uses: ./.github/workflows/workload-long-lived.yml
-    with:
-      id: uptime
-      location: ${{ inputs.location }}
-      cleanup: false
