.

diff --git a/.github/workflows/vm-workload-stress-tests.yml b/.github/workflows/vm-workload-stress-tests.yml
--- a/.github/workflows/vm-workload-stress-tests.yml
+++ b/.github/workflows/vm-workload-stress-tests.yml
@@ -113,6 +113,7 @@ jobs:
   vm-stress-tests:
     name: ${{ inputs.id || 'vm-stress-tests' }}
     runs-on: ubuntu-latest
+    continue-on-error: true # This only works because historical results tracks per job and failing jobs are still red
     steps:
 
       - name: Checkout
@@ -253,11 +254,11 @@ jobs:
               tail -n 20 check.log
             fi
           done
-          set -e
           exit 0
 
       - name: Check for errors
         run: |
+          set +e
           echo Full check_loop.log:
           cat check.log
           grep -F ERROR check.log
@@ -265,6 +266,7 @@ jobs:
             echo Found errors in check log.
             exit 1
           fi
+          exit 0
 
       - name: Log into Azure
         uses: azure/login@v2
@@ -273,39 +275,38 @@ jobs:
           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
           subscription-id: ${{ vars.SUBSCRIPTION }}
 
-      # TODO: find a better way to fetch dmesg - Azure truncates the output
       - name: Check dmesg
-        if: always()
         run: |
-            dmesg_file="dmesg.log"
+          set +e
+          dmesg_file="dmesg.log"
 
-            c-aci-testing vm exec --deployment-name $DEPLOYMENT_NAME 'Get-Item C:\*\dmesg*.log | foreach { echo ""; echo ""; echo $_.FullName; cat -Raw $_ } > C:\all-dmesg.log'
-            c-aci-testing vm cat --deployment-name $DEPLOYMENT_NAME 'C:\all-dmesg.log' > $dmesg_file
-            if [ $? -ne 0 ]; then
-              echo "Failed to get dmesg:"
-              cat $dmesg_file
-              exit 1
-            fi
-
-            found_sus_message=""
-            grep -F '] hv_storvsc' $dmesg_file && found_sus_message="hv_storvsc"
-            grep -i segfault $dmesg_file && found_sus_message="segfault"
-            grep -i 'protection fault' $dmesg_file && found_sus_message="protection-fault"
-            grep -v 'watchdog: BUG: soft lockup' $dmesg_file | grep 'BUG:' && found_sus_message="kernel-bug"
-            grep -v 'hv_send_ipi_mask' $dmesg_file | grep 'WARNING:' && found_sus_message="kernel-bug"
-            # grep 'RIP:' $dmesg_file && found_sus_message="kernel-backtrace"
-
+          c-aci-testing vm exec --deployment-name $DEPLOYMENT_NAME 'Get-Item C:\*\dmesg*.log | foreach { echo ""; echo ""; echo $_.FullName; cat -Raw $_ } > C:\all-dmesg.log'
+          c-aci-testing vm cat --deployment-name $DEPLOYMENT_NAME 'C:\all-dmesg.log' > $dmesg_file
+          if [ $? -ne 0 ]; then
+            echo "Failed to get dmesg."
             cat $dmesg_file
+            exit 1
+          fi
 
-            if [ -n "$found_sus_message" ]; then
-              echo "Found suspicious message in dmesg: $found_sus_message"
-              exit 1
-            fi
+          found_sus_message=""
+          grep -F '] hv_storvsc' $dmesg_file && found_sus_message="hv_storvsc"
+          grep -i segfault $dmesg_file && found_sus_message="segfault"
+          grep -i 'protection fault' $dmesg_file && found_sus_message="protection-fault"
+          grep -v 'watchdog: BUG: soft lockup' $dmesg_file | grep 'BUG:' && found_sus_message="kernel-bug"
+          grep -v 'hv_send_ipi_mask' $dmesg_file | grep 'WARNING:' && found_sus_message="kernel-bug"
+          # grep 'RIP:' $dmesg_file && found_sus_message="kernel-backtrace"
 
-            if [ ! -s $dmesg_file ]; then
-              echo "No dmesg output found"
-              exit 1
-            fi
+          cat $dmesg_file
+
+          if [ -n "$found_sus_message" ]; then
+            echo "Found suspicious message in dmesg: $found_sus_message"
+            exit 1
+          fi
+
+          if [ ! -s $dmesg_file ]; then
+            echo "No dmesg output found"
+            exit 1
+          fi
 
       - name: Remove VM
         run: |
